{
    "name": "Meeting Minutes",
    "version": "18.0.1.0.0",
    "category": "Discuss",
    "sequence": 1,
    "author": "AMADIO",
    "website": "https://amadio.io",
    "license": "OPL-1",
    "price": 59,
    "currency": "EUR",
    "depends": ["calendar", "mail"],
    "installable": True,
    "auto_install": False,
    "application": True,
    "summary": "Capture structured meeting minutes directly in Odoo calendar events. Record decisions, assign action items with owners and due dates, track completion. Auto-email minutes to all attendees.",
    "description": "Capture structured meeting minutes directly in Odoo calendar events. Record decisions, assign action items with owners and due dates, track completion. Auto-email minutes to all attendees.",
    "images": ["static/description/icon.png"],
    "external_dependencies": {"python": [], "bin": []},
}
