{
    "name": "Purchase Approval Matrix",
    "version": "18.0.1.0.0",
    "category": "Purchase",
    "sequence": 1,
    "author": "AMADIO",
    "website": "https://amadio.io",
    "license": "OPL-1",
    "price": 89,
    "currency": "EUR",
    "depends": ["purchase", "mail"],
    "installable": True,
    "auto_install": False,
    "application": True,
    "summary": "Configure multi-level PO approval tiers based on amount thresholds. POs auto-route to the right approver. No more bypassed controls or over-budget purchases.",
    "description": "Configure multi-level PO approval tiers based on amount thresholds. POs auto-route to the right approver. No more bypassed controls or over-budget purchases.",
    "images": ["static/description/banner.png", "static/description/icon.png"],
    "external_dependencies": {"python": [], "bin": []},
}
