{
    "name": "Sales Commission Tracker",
    "version": "18.0.1.0.0",
    "category": "Sales",
    "sequence": 1,
    "author": "AMADIO",
    "website": "https://amadio.io",
    "license": "OPL-1",
    "price": 99,
    "currency": "EUR",
    "depends": ["sale", "account", "mail"],
    "installable": True,
    "auto_install": False,
    "application": True,
    "summary": "Configure commission rules by sales rep, team, product category, or customer. Auto-calculate commissions on paid invoices. Monthly commission statements with approval workflow.",
    "description": "Configure commission rules by sales rep, team, product category, or customer. Auto-calculate commissions on paid invoices. Monthly commission statements with approval workflow.",
    "images": ["static/description/icon.png"],
    "external_dependencies": {"python": [], "bin": []},
}
