{
    "name": "Hr Onboarding Checklist",
    "version": "18.0.1.0.0",
    "category": "Human Resources",
    "sequence": 1,
    "author": "AMADIO",
    "website": "https://amadio.io",
    "license": "OPL-1",
    "price": 79,
    "currency": "EUR",
    "depends": ["hr", "mail"],
    "installable": True,
    "auto_install": False,
    "application": True,
    "summary": "Structured onboarding workflows for new hires — HR tasks, IT provisioning, document collection, policy acknowledgments. Auto-launch on employee creation.",
    "description": "Structured onboarding workflows for new hires — HR tasks, IT provisioning, document collection, policy acknowledgments. Auto-launch on employee creation.",
    "images": ["static/description/icon.png"],
    "external_dependencies": {"python": [], "bin": []},
}
