{
    "name": "Asset Maintenance Scheduler",
    "version": "18.0.1.0.0",
    "category": "Accounting",
    "sequence": 1,
    "author": "AMADIO",
    "website": "https://amadio.io",
    "license": "OPL-1",
    "price": 89,
    "currency": "EUR",
    "depends": ["account", "mail"],
    "installable": True,
    "auto_install": False,
    "application": True,
    "summary": "Link preventive maintenance schedules directly to Odoo fixed assets. Configure service intervals (mileage, time, usage), receive alerts when maintenance is due.",
    "description": "Link preventive maintenance schedules directly to Odoo fixed assets. Configure service intervals (mileage, time, usage), receive alerts when maintenance is due.",
    "images": ["static/description/icon.png"],
    "external_dependencies": {"python": [], "bin": []},
}
